module Messenger 
{
#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message subject_id"  
  
  struct Message 
  {   
    string from;    
    string subject;    
    long subject_id;    
    string text;    
    long count;
  };
};


module Sensors
{
  #pragma DCPS_DATA_TYPE "Sensors::Sensor"
  #pragma DCPS_DATA_KEY "Sensors::Sensor my_uuid"

  typedef string<16> uuid;
  struct Sensor
  {
    uuid my_uuid;
    float reading;
    string comment;
  };
};

